<a href="https://colab.research.google.com/github/abhx7/Deep-Learning-with-PyTorch---GANS/blob/main/01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to PyTorch Tensors

A tensor is a number, vector, matrix or any n-dimensional array. Fundamentally, PyTorch is a library for processing tensors. We will be looking into the workings of some functions of this library through examples.

- linspace
- split
- cat
- trig functions
- randint

Before we begin, let's install and import PyTorch

## Lesson 1 Summary

* In the first lesson, we leart how to work with tensors and generating its gradient as it would be useful for linear regression.
* We also discussed its interoperability with numpy and why pytorch is needed inspite of numpy covering most of its abilities.
* Next, we learnt to [train a model using linear regression through gradient descent](https://jovian.ai/aakashns/02-linear-regression). We did this first manually and then through pytorch inbuilts
* Finally we were introduced a bit to the [concept of machine learning in contrast to classical programming as well as linear regression being the most simple neural network](https://jovian.ai/aakashns/machine-learning-intro).

In [ ]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [ ]:
# Import torch and other required modules
import torch

## Function 1 - torch.linspace(a,b,n)

Creates a one dimensional tensor with n elements equally spaced from a to b, including the both ends.

In [ ]:
# Example 1 - working
t1a=torch.linspace (0,10,101);
t1a

tensor([ 0.0000,  0.1000,  0.2000,  0.3000,  0.4000,  0.5000,  0.6000,  0.7000,
         0.8000,  0.9000,  1.0000,  1.1000,  1.2000,  1.3000,  1.4000,  1.5000,
         1.6000,  1.7000,  1.8000,  1.9000,  2.0000,  2.1000,  2.2000,  2.3000,
         2.4000,  2.5000,  2.6000,  2.7000,  2.8000,  2.9000,  3.0000,  3.1000,
         3.2000,  3.3000,  3.4000,  3.5000,  3.6000,  3.7000,  3.8000,  3.9000,
         4.0000,  4.1000,  4.2000,  4.3000,  4.4000,  4.5000,  4.6000,  4.7000,
         4.8000,  4.9000,  5.0000,  5.1000,  5.2000,  5.3000,  5.4000,  5.5000,
         5.6000,  5.7000,  5.8000,  5.9000,  6.0000,  6.1000,  6.2000,  6.3000,
         6.4000,  6.5000,  6.6000,  6.7000,  6.8000,  6.9000,  7.0000,  7.1000,
         7.2000,  7.3000,  7.4000,  7.5000,  7.6000,  7.7000,  7.8000,  7.9000,
         8.0000,  8.1000,  8.2000,  8.3000,  8.4000,  8.5000,  8.6000,  8.7000,
         8.8000,  8.9000,  9.0000,  9.1000,  9.2000,  9.3000,  9.4000,  9.5000,
         9.6000,  9.7000,  9.8000,  9.90


Creates a one dimensional tensor with 101 elements equally spaced from 0 to 10, including the both ends.

In [ ]:
# Example 2 - working
t1b=torch.linspace (5,-5,11,dtype=torch.int8);
t1b

tensor([ 5,  4,  3,  2,  1,  0, -1, -2, -3, -4, -5], dtype=torch.int8)

Creates a one dimensional tensor with 11 integer elements equally spaced from -5 to 5, including the both ends.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.linspace(5,0,-3)

RuntimeError: ignored

The number of elements need to be created must be a whole number for the tensor to be created.


Points to Note:
*   If a is greater than b, a descending order tensor is created.
*   We can also mention the data type of the tensor in the decleration.

Let's save our work using Jovian before continuing.

In [ ]:
!pip install jovian --upgrade --quiet

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.6/68.6 kB 1.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done


In [ ]:
import jovian

In [ ]:
jovian.commit(project='01-tensor-operations-abhi')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 2 - torch.cat(t1,t2)

Combining the elements of 2 tensors of same shape to create one tensor

In [ ]:
# Example 1 - working
t1=torch.tensor([[1,2],[2,3]]);
t2=torch.tensor([[1,4],[4,1]]);
t3=torch.cat((t1,t2));
t3

Combines the elements of 2 two dimensional tensors one after the other as that is the default operation.

In [ ]:
# Example 2 - working
t1=torch.tensor([[[1,1],[1,1]],[[2,2],[2,2]]]);
t2=torch.tensor([[[1,1],[1,1]],[[4,4],[4,4]]]);
t3=torch.cat((t1,t2),2);

Combines the row elements of 2 three dimensional tensors as it is given to add along 1st dimension.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
t1=torch.tensor([[1,2],[2,3]]);
t2=torch.tensor([[1,4],[4,1]]);
t3=torch.cat((t1,t2),2);
t3

Concatenation is not possible in higher dimension than the input tensor dimesnions

Points to Note:

*   torch.cat() can be seen as an inverse operation for torch.split()
*   Non-empty tensors provided must have the same shape, except in the cat dimension (not necessary in cat dimension).



In [ ]:
jovian.commit(project='01-tensor-operations-abhi')

## Function 3 - torch.randint(low,high,n)

Generates a tensor filled with 'n' random integers generated uniformly between low (inclusive) and high (exclusive).

In [ ]:
# Example 1 - working
torch.randint(0,10,(10,))

Creates a 1D tensor of 10 elements from any integer from 0 to 9.

In [ ]:
# Example 2 - working
torch.randint(-5,5,(2,2,2))

Creates a 3D tensor of shape [2,2,2] with elements from any integer from -5 to 5.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.randint(3,(2,2,-1))

RuntimeError: ignored

The size of each dimension of tensor created must be a non negative integer.

Points to Note:

*   0 is the default low value.
*   generator (torch.Generator, optional) – a pseudorandom number generator for sampling



In [ ]:
jovian.commit(project='01-tensor-operations-abhi')

## Function 4 - torch.cos()/torch.sin()/torch.log()//

Returns a new tensor with the cosine/sin/whatever trignomteric operation output of the elements of input

In [ ]:
# Example 1 - working
t1=torch.tensor([[0,0.52],[1.57,1.57]])
torch.sin(t1)

tensor([[0.0000, 0.4969],
        [1.0000, 1.0000]])

returns a tensor with the sin of all elements of original tensor.

In [ ]:
# Example 2 - working
t1=torch.tensor([[0,0.52],[1.57,1.57]])
torch.log(t1)

tensor([[   -inf, -0.6539],
        [ 0.4511,  0.4511]])

returns a tensor with the log of all elements of original tensor.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
t1=torch.tensor([[0,1],[-1,3]])
torch.asin(t1)

tensor([[ 0.0000,  1.5708],
        [-1.5708,     nan]])

couldnt find a case where it breaks!!

Points to Note:
- the function is applied uniformly to all the elements of the tensor, regardless of the fact if the input falls in the domain of the mathematical function and one should be careful as it does not show that as an error

In [ ]:
jovian.commit(project='01-tensor-operations-abhi')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 5 - torch.normal()

Generates a tensor of random numbers drawn from separate normal distributions whose mean and standard deviation are given.

In [ ]:
# Example 1 - working
torch.normal(mean=0,std=1,size=(5,))

tensor([ 0.8870, -1.2236,  0.4472,  0.5753,  0.6565])

Returns a tensor of random numbers drawn from a single normal distributions whose mean is 0 and standard deviation is 1.

In [ ]:
# Example 2 - working
torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1))

Returns a tensor of random numbers drawn from seperate normal distributions whose mean and standard deviation are given.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
torch.normal(mean=-1, std=2.4,size=(2,4))

tensor([[-3.0261, -1.2554,  0.4488,  2.8021],
        [-2.0462,  0.5893,  0.1505,  1.4204]])

couldn't find any!!

Points to Note:
- The mean is a tensor with the mean of each output element’s normal distribution
- The std is a tensor with the standard deviation of each output element’s normal distribution
- The shapes of mean and std don’t need to match, but the total number of elements in each tensor need to be the same.

In [ ]:
jovian.commit(project='01-tensor-operations-abhi')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Reference Links
Links to my references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [ ]:
jovian.commit(project='01-tensor-operations-abhi')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.
